export interface WordClue {
  word: string;
  clue: string;
}

// Banco de palabras de fútbol (jugadores, clubes, términos, mundiales).
// Las palabras van en mayúsculas, sin espacios ni tildes (la Ñ está permitida).
export const FOOTBALL_WORD_BANK: WordClue[] = [
  { word: "MESSI", clue: "Ganó el Mundial 2022 y juega en el Inter Miami" },
  { word: "DIBU", clue: "Atajó el penal decisivo contra Francia en Qatar" },
  { word: "PELOTA", clue: "Sin ella no hay partido" },
  { word: "ARQUERO", clue: "El único que puede usar las manos dentro del área" },
  { word: "PENAL", clue: "Tiro desde los once metros" },
  { word: "OFFSIDE", clue: "Posición adelantada, en criollo: 'fuera de juego'" },
  { word: "CANCHA", clue: "El campo de juego" },
  { word: "ARBITRO", clue: "El que dirige el partido con el silbato" },
  { word: "CORNER", clue: "Tiro de esquina" },
  { word: "MUNDIAL", clue: "Se juega cada cuatro años" },
  { word: "SCALONI", clue: "Director técnico campeón del mundo en 2022" },
  { word: "BOCA", clue: "Club de la Ribera, xeneize" },
  { word: "RIVER", clue: "Club Millonario de Núñez" },
  { word: "MARADONA", clue: "El Diez, autor de 'la mano de Dios'" },
  { word: "ALBICELESTE", clue: "Apodo de la selección argentina" },
  { word: "GOLEADOR", clue: "El que más goles convierte" },
  { word: "TRAVESANO", clue: "El palo horizontal del arco" },
  { word: "AMARILLA", clue: "Tarjeta de amonestación" },
  { word: "ROJA", clue: "Tarjeta de expulsión" },
  { word: "HINCHA", clue: "El fanático que alienta a su equipo" },
  { word: "ESTADIO", clue: "Lugar donde se juegan los partidos" },
  { word: "CAPITAN", clue: "Lleva la cinta en el brazo" },
  { word: "SUPLENTE", clue: "Jugador que empieza en el banco" },
  { word: "LATERAL", clue: "Defensor que juega por la banda" },
  { word: "VOLANTE", clue: "Jugador de mediocampo" },
  { word: "DELANTERO", clue: "Jugador de ataque, cerca del arco rival" },
  { word: "TECNICO", clue: "El que dirige al equipo desde afuera" },
  { word: "REFERI", clue: "Otra forma de llamar al árbitro" },
  { word: "ANGOLA", clue: "No es de fútbol, pero rima con... nada, es un país" },
  { word: "COPA", clue: "Trofeo que se levanta al ganar" },
  { word: "EQUIPO", clue: "Once jugadores más el plantel completo" },
  { word: "TITULAR", clue: "Jugador que arranca el partido de entrada" },
  { word: "BARRA", clue: "Grupo organizado de hinchas" },
  { word: "CAMISETA", clue: "Prenda que identifica a cada club" },
  { word: "BOTIN", clue: "Calzado especial para jugar al fútbol" },
  { word: "PICADO", clue: "Partido informal entre amigos" },
  { word: "CHILENA", clue: "Remate acrobático de espaldas al arco" },
  { word: "CABEZAZO", clue: "Remate hecho con la cabeza" },
  { word: "TIRO", clue: "Disparo al arco" },
  { word: "PASE", clue: "Entrega del balón a un compañero" },
  { word: "GAMBETA", clue: "Amague para dejar atrás a un rival" },
  { word: "TACLE", clue: "Entrada para quitar la pelota" },
  { word: "BANDERIN", clue: "Marca los límites del córner" },
  { word: "ALARGUE", clue: "Tiempo extra cuando hay empate" },
  { word: "VESTUARIO", clue: "Lugar donde se cambian los jugadores" },
  { word: "PLANTEL", clue: "Conjunto de jugadores de un equipo" },
  { word: "ENGANCHE", clue: "El armador del equipo, entre volantes y delanteros" },
  { word: "MARCADOR", clue: "Muestra el resultado del partido" },
  { word: "SILBATO", clue: "Instrumento que usa el árbitro" },
  { word: "CANO", clue: "Amague entre las piernas del rival, gambeta clásica" },
  { word: "VAR", clue: "Sistema de video que revisa jugadas polémicas" },
  { word: "AGUANTE", clue: "Fidelidad incondicional del hincha a su club" },
  { word: "CLASICO", clue: "Partido entre los dos rivales históricos de una ciudad" },
  { word: "DESCENSO", clue: "Lo que le pasa al equipo que pierde la categoría" },
  { word: "ASCENSO", clue: "Subir a una categoría superior" },
  { word: "ENTRENADOR", clue: "Otra forma de decir director técnico" },
  { word: "PICHICHI", clue: "Premio al máximo goleador de un torneo" },
  { word: "VESTIDOR", clue: "Sinónimo de vestuario" },
  { word: "TRIBUNA", clue: "Sector del estadio donde se sientan los hinchas" },
  { word: "RELATOR", clue: "El que narra el partido por radio o televisión" },
  { word: "FUERA", clue: "Cuando la pelota sale de la cancha" },

  // Balón de Oro
  { word: "CRISTIANO", clue: "Rival histórico de Messi, ganador de 5 Balones de Oro" },
  { word: "MODRIC", clue: "Croata que cortó la racha Messi-Cristiano y ganó el Balón de Oro 2018" },
  { word: "BENZEMA", clue: "Delantero francés, Balón de Oro 2022" },
  { word: "KAKA", clue: "Brasileño, Balón de Oro 2007" },
  { word: "RONALDINHO", clue: "Brasileño de sonrisa inolvidable, Balón de Oro 2005" },
  { word: "ZIDANE", clue: "Balón de Oro 1998, hoy reconocido como entrenador" },
  { word: "NEYMAR", clue: "Estrella brasileña que jugó en Barcelona, PSG y Al-Hilal" },
  { word: "MBAPPE", clue: "Delantero francés, campeón del mundo en 2018 siendo muy joven" },
  { word: "HAALAND", clue: "Delantero noruego goleador del Manchester City" },
  { word: "LEWANDOWSKI", clue: "Goleador histórico polaco del Bayern Múnich" },

  // Goleadores históricos
  { word: "KLOSE", clue: "Alemán, máximo goleador histórico de los Mundiales" },
  { word: "GIROUD", clue: "Máximo goleador histórico de la selección de Francia" },
  { word: "PELE", clue: "Leyenda brasileña tricampeón del mundo" },
  { word: "BATISTUTA", clue: "Goleador histórico argentino apodado 'Bati Gol'" },

  // Selecciones campeonas del mundo
  { word: "ARGENTINA", clue: "Selección campeona del mundo en 1978, 1986 y 2022" },
  { word: "BRASIL", clue: "Selección con más títulos mundiales: cinco" },
  { word: "ALEMANIA", clue: "Selección campeona del mundo en 2014" },
  { word: "FRANCIA", clue: "Selección campeona del mundo en 1998 y 2018" },
  { word: "URUGUAY", clue: "Ganó el primer Mundial de la historia, en 1930" },
  { word: "ESPAÑA", clue: "Selección campeona del mundo en 2010" },
  { word: "ITALIA", clue: "Selección campeona del mundo en 2006" },

  // Goleadores y premios
  { word: "MESSI", clue: "Máximo goleador histórico de LaLiga de España" },
  { word: "SHEARER", clue: "Máximo artillero histórico de la Premier League inglesa" },
  { word: "PIOLA", clue: "Apellido del máximo goleador de la historia de la Serie A italiana" },
  { word: "PALERMO", clue: "Máximo goleador histórico de Boca Juniors, 'El Titán'" },
  { word: "LABRUNA", clue: "Máximo artillero histórico de River Plate y de los Superclásicos" },
  { word: "PICHICHI", clue: "Famoso trofeo y apodo para el máximo goleador de la liga española" },

  // Apodos de jugadores
  { word: "PULGA", clue: "El apodo clásico de Lionel Messi desde sus inicios" },
  { word: "DIBU", clue: "Apodo del arquero campeón del mundo Emiliano Martínez" },
  { word: "FIDEO", clue: "Sobrenombre clásico de Ángel Di María por su físico delgado" },

  // Apodos de clubes argentinos
  { word: "XENEIZE", clue: "Apodo tradicional de los hinchas y del club Boca Juniors" },
  { word: "MILLONARIO", clue: "Apodo emblemático con el que se conoce a River Plate" },
  { word: "PINCHARRATA", clue: "Histórico apodo del club Estudiantes de La Plata" },
  { word: "CUERVO", clue: "Apodo tradicional de los hinchas de San Lorenzo de Almagro" },
  { word: "GLOBO", clue: "Apodo característico del club Huracán de Parque Patricios" },
  { word: "LEPRA", clue: "Sobrenombre histórico con el que se conoce a Newell's Old Boys" },
  { word: "PIRATA", clue: "Apodo clásico del club Belgrano de Córdoba" },
  { word: "MATADOR", clue: "Apodo principal con el que se identifica al club Talleres de Córdoba" },
  { word: "BICHO", clue: "Apodo de Argentinos Juniors, club donde se formó Diego Maradona" },
  { word: "LOBO", clue: "Apodo histórico del club Gimnasia y Esgrima La Plata" },
  { word: "CANALLA", clue: "Apodo popular de los hinchas y equipo de Rosario Central" },
  { word: "FORTIN", clue: "Sobrenombre del estadio del club Vélez Sarsfield" },
  { word: "LANUS", clue: "Club apodado 'El Granate' por el color característico de su camiseta" },

  // Apodos de clubes europeos
  { word: "COLCHONEROS", clue: "Apodo tradicional del Atlético de Madrid" },
  { word: "MERENGUES", clue: "Sobrenombre clásico con el que se conoce al Real Madrid" },

  // Apodos de clubes brasileños
  { word: "MENGAO", clue: "Popular apodo del club Flamengo de Río de Janeiro" },
  { word: "TIMAO", clue: "Apodo clásico de la hinchada y el equipo del Corinthians" },
  { word: "VERDAO", clue: "Sobrenombre con el que se conoce al Palmeiras de Brasil" },
  { word: "PEIXE", clue: "Apodo del Santos de Brasil, club donde brillaron Pelé y Neymar" },
  { word: "GALO", clue: "Apodo del Atlético Mineiro, representado por un gallo" },
  { word: "COLORADO", clue: "Apodo del club Internacional de Porto Alegre por el color de su camiseta" },
  { word: "RAPOSA", clue: "Apodo del Cruzeiro de Brasil, que significa zorro en portugués" },
  { word: "TRICOLOR", clue: "Apodo que comparten grandes clubes brasileros como São Paulo y Fluminense" },

  // Campeones y curiosidades
  { word: "INDEPENDIENTE", clue: "El 'Rey de Copas', club con más Copas Libertadores ganadas" },
  { word: "MADRID", clue: "Club con mayor cantidad de títulos de UEFA Champions League" },
  { word: "SEVILLA", clue: "Máximo campeón en la historia de la UEFA Europa League" },
  { word: "BRASIL", clue: "Única selección que ganó 5 Mundiales de la FIFA" },
  { word: "URUGUAY", clue: "Junto con Argentina, uno de los máximos ganadores de la Copa América" },
  { word: "RACING", clue: "Primer club argentino en ganar la Copa Intercontinental (1967)" },
  { word: "ALUMNI", clue: "Mítico club amateur multicampeón surgido de un colegio inglés" },
];
