export interface WordClue {
  word: string;
  clue: string;
}

// Banco de palabras de fútbol (jugadores, clubes, términos, mundiales).
// Las palabras van en mayúsculas, sin espacios ni tildes (la Ñ está permitida).
export const FOOTBALL_WORD_BANK: WordClue[] = [
  { word: "MESSI", clue: "Ganó el Mundial 2022 y juega en el Inter Miami" },
  { word: "DIBU", clue: "Atajó el penal decisivo contra Francia en Qatar" },
  { word: "PELOTA", clue: "Sin ella no hay partido" },
  { word: "ARQUERO", clue: "El único que puede usar las manos dentro del área" },
  { word: "PENAL", clue: "Tiro desde los once metros" },
  { word: "OFFSIDE", clue: "Posición adelantada, en criollo: 'fuera de juego'" },
  { word: "CANCHA", clue: "El campo de juego" },
  { word: "ARBITRO", clue: "El que dirige el partido con el silbato" },
  { word: "CORNER", clue: "Tiro de esquina" },
  { word: "MUNDIAL", clue: "Se juega cada cuatro años" },
  { word: "SCALONI", clue: "Director técnico campeón del mundo en 2022" },
  { word: "BOCA", clue: "Club de la Ribera, xeneize" },
  { word: "RIVER", clue: "Club Millonario de Núñez" },
  { word: "MARADONA", clue: "El Diez, autor de 'la mano de Dios'" },
  { word: "ALBICELESTE", clue: "Apodo de la selección argentina" },
  { word: "GOLEADOR", clue: "El que más goles convierte" },
  { word: "TRAVESANO", clue: "El palo horizontal del arco" },
  { word: "AMARILLA", clue: "Tarjeta de amonestación" },
  { word: "ROJA", clue: "Tarjeta de expulsión" },
  { word: "HINCHA", clue: "El fanático que alienta a su equipo" },
  { word: "ESTADIO", clue: "Lugar donde se juegan los partidos" },
  { word: "CAPITAN", clue: "Lleva la cinta en el brazo" },
  { word: "SUPLENTE", clue: "Jugador que empieza en el banco" },
  { word: "LATERAL", clue: "Defensor que juega por la banda" },
  { word: "VOLANTE", clue: "Jugador de mediocampo" },
  { word: "DELANTERO", clue: "Jugador de ataque, cerca del arco rival" },
  { word: "TECNICO", clue: "El que dirige al equipo desde afuera" },
  { word: "REFERI", clue: "Otra forma de llamar al árbitro" },
  { word: "ANGOLA", clue: "No es de fútbol, pero rima con... nada, es un país" },
  { word: "COPA", clue: "Trofeo que se levanta al ganar" },
  { word: "EQUIPO", clue: "Once jugadores más el plantel completo" },
  { word: "TITULAR", clue: "Jugador que arranca el partido de entrada" },
  { word: "BARRA", clue: "Grupo organizado de hinchas" },
  { word: "CAMISETA", clue: "Prenda que identifica a cada club" },
  { word: "BOTIN", clue: "Calzado especial para jugar al fútbol" },
  { word: "PICADO", clue: "Partido informal entre amigos" },
  { word: "CHILENA", clue: "Remate acrobático de espaldas al arco" },
  { word: "CABEZAZO", clue: "Remate hecho con la cabeza" },
  { word: "TIRO", clue: "Disparo al arco" },
  { word: "PASE", clue: "Entrega del balón a un compañero" },
  { word: "GAMBETA", clue: "Amague para dejar atrás a un rival" },
  { word: "TACLE", clue: "Entrada para quitar la pelota" },
  { word: "BANDERIN", clue: "Marca los límites del córner" },
  { word: "ALARGUE", clue: "Tiempo extra cuando hay empate" },
  { word: "VESTUARIO", clue: "Lugar donde se cambian los jugadores" },
  { word: "PLANTEL", clue: "Conjunto de jugadores de un equipo" },
  { word: "ENGANCHE", clue: "El armador del equipo, entre volantes y delanteros" },
  { word: "MARCADOR", clue: "Muestra el resultado del partido" },
  { word: "SILBATO", clue: "Instrumento que usa el árbitro" },
  { word: "CANO", clue: "Amague entre las piernas del rival, gambeta clásica" },
  { word: "VAR", clue: "Sistema de video que revisa jugadas polémicas" },
  { word: "AGUANTE", clue: "Fidelidad incondicional del hincha a su club" },
  { word: "CLASICO", clue: "Partido entre los dos rivales históricos de una ciudad" },
  { word: "DESCENSO", clue: "Lo que le pasa al equipo que pierde la categoría" },
  { word: "ASCENSO", clue: "Subir a una categoría superior" },
  { word: "ENTRENADOR", clue: "Otra forma de decir director técnico" },
  { word: "PICHICHI", clue: "Premio al máximo goleador de un torneo" },
  { word: "VESTIDOR", clue: "Sinónimo de vestuario" },
  { word: "TRIBUNA", clue: "Sector del estadio donde se sientan los hinchas" },
  { word: "RELATOR", clue: "El que narra el partido por radio o televisión" },
  { word: "FUERA", clue: "Cuando la pelota sale de la cancha" },
];
